<?php

// This file is automatically generated and modified by phpMyBackupPro 2.5

$CONF['sql_user']=ue('root');
$CONF['sql_host']=ue('127.0.0.1');
$CONF['sql_db']=ue('db_risk');
$CONF['ftp_use']=ue('0');
$CONF['email_use']=ue('0');
$CONF['sitename']=ue('localhost:8080/risk2');
$CONF['lang']=ue('english');
$CONF['import_error']=ue('1');
$CONF['no_login']=ue('1');
$CONF['login']=ue('0');
$CONF['dir_backup']=ue('1');
$CONF['dir_rec']=ue('1');
$CONF['email']=ue('mail@example.com');
$CONF['ftp_pasv']=ue('0');
$CONF['ftp_del']=ue('0');
$CONF['ftp_server']=ue('example.com');
$CONF['ftp_user']=ue('');
$CONF['ftp_port']=ue('21');
$CONF['date']=ue('%x %X');
$CONF['del_time']=ue('3');
$CONF['del_number']=ue('5');
$CONF['timelimit']=ue('30');
$CONF['confirm']=ue('1');
$CONF['stylesheet']=ue('standard');
$CONF['ftp_path']=ue('');
$CONF['ftp_passwd']=ue('');
$CONF['sql_passwd']=ue('123456');

$PMBP_SYS_VAR['last_scheduled']=ue('');
$PMBP_SYS_VAR['this_login']=ue('');
$PMBP_SYS_VAR['last_login']=ue('');
$PMBP_SYS_VAR['dir_lists']=ue('1');
$PMBP_SYS_VAR['memory_limit']=ue('4000000');
$PMBP_SYS_VAR['except_tables']=ue('');
$PMBP_SYS_VAR['scheduled_debug']=ue('0');
$PMBP_SYS_VAR['schedule_all_dbs']=ue('0');
$PMBP_SYS_VAR['ftp_timeout']=ue('10');
$PMBP_SYS_VAR['dir_email_backup']=ue('0');
$PMBP_SYS_VAR['C_disable_config']=ue('0');
$PMBP_SYS_VAR['C_disable_sqlquery']=ue('0');
$PMBP_SYS_VAR['B_backup_chmod']=ue('0700');
$PMBP_SYS_VAR['F_dbs']=ue('db_risk');
$PMBP_SYS_VAR['F_comment']=ue('test backup');
$PMBP_SYS_VAR['F_tables']=ue('on');
$PMBP_SYS_VAR['F_data']=ue('on');
$PMBP_SYS_VAR['F_drop']=ue('on');
$PMBP_SYS_VAR['F_compression']=ue('');
$PMBP_SYS_VAR['F_ftp_dirs']=ue('');
$PMBP_SYS_VAR['F_ftp_dirs_2']=ue('|');
$PMBP_SYS_VAR['F_packed']=ue('on');
$PMBP_SYS_VAR['F_updates']=ue('1');
$PMBP_SYS_VAR['F_ffadd']=ue('1');
$PMBP_SYS_VAR['EXS_scheduled_file']=ue('scheduled.php');
$PMBP_SYS_VAR['EXS_scheduled_dir']=ue('D:/xampp/htdocs/risk2/backup/');
$PMBP_SYS_VAR['EXS_period']=ue('*0');
$PMBP_SYS_VAR['security_key']=ue('303ea88c3a5df3a9259b9478fd8c7235');

?>